language: objective-c
osx_image: xcode10
xcode_project: web3swift.xcworkspace # path to your xcodeproj folder
xcode_scheme: web3swift-iOS
xcode_destination: platform=iOS Simulator, OS=12.0, name=iPhone X
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
  - xcodebuild -scheme web3swift-iOS -workspace web3swift.xcworkspace -sdk iphonesimulator build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
