name: "Web3swift CI"

on: 
  push:
    branches:
      - master
      - develop
      - hotfix
      - github-actions
    paths:
      - Sources/**
      - 'Tests/**'
      - 'web3swift*/**'
      - '.github/workflows/**'

concurrency: 
  group: ci
  cancel-in-progress: true
jobs:
  SPM:
    name: Swift Package Manager 5.4
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.5.1.app/Contents/Developer
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        destination: ['OS=14.5,name=iPhone 12']
    steps:
      - uses: actions/checkout@v2
      - name: Resolve dependencies
        run: swift package resolve
      - name: Run local test
        run: swift test --filter localTests